### ISSUE TITLE
Misalignment of overlay with high dpi

### ISSUE THREAD

**Issue by factormystic** [lolp1/Overlay.NET#5] opened 2017-02-18 21:08 UTC
I was only able to get the WPF demo working, but that demonstrates the problem. Moving or resizing the window, the corresponding adjustment of the overlay is off by (apparently) the dpi scale factor.

**Comment by abratar** [comment] 2017-02-18 23:05
you mean the dpi of your screen or your mouse? for me it looks right

**Comment by lolp1** [comment] 2017-02-18 23:09
I need more details. The full code used for the overlay that produces the bug and circumstances that it happens in. Otherwise I can not reproduce it and fix it on my end because I do not have this issue.

**Comment by factormystic** [comment] 2017-02-19 00:43
Screen DPI. Here's an example screencap at 150%. When I drag notepad, the overlay is translating more than the window is actually moving. I'm not talking about the jitter, I think that may be due in part to my screencap software. I'm just talking about how the alignment is different when I move notepad.

![](https://thumbs.gfycat.com/DaringGrouchyCivet-size_restricted.gif)

**Comment by factormystic** [comment] 2017-02-20 18:50
It's not, the lag is an artifact of the screen capture. Just look at whats happening in each corner. Here's a comparison:

![corner2](https://cloud.githubusercontent.com/assets/43428/23138092/7acc8116-f773-11e6-8e08-2b3706410411.jpg)

![corner1](https://cloud.githubusercontent.com/assets/43428/23138098/7ebf2a1c-f773-11e6-9b5c-0a83567e88f3.jpg)

**Comment by lolp1** [comment] 2017-03-17 08:25
I have had no other reports of the described issue, and have been unable to reproduce the issue testing it on both x86 and x64 windows 10 platforms in various processes using the demo. 

For this reason, I am going to close the issue for now. I did just recently update the project, so feel free to try again and if the issue still persist reopen the issue with more information if possible. Windows version (preferably the current upgrade patch it is on as well), process architecture (x86 or x64) and any relevant debugging attempts, and full code if not using the stock demo would be ideal. Thanks.

**Closed by lolp1** 2017-03-17 08:25 UTC
