### ISSUE TITLE
BUG DirectX Overlay showing when window is not focused

### ISSUE THREAD

**Issue by Traderain** [lolp1/Overlay.NET#3] opened 2016-12-14 17:46 UTC

**Comment by lolp1** [comment] 2016-12-15 04:28
Confirmed bug, will look to fixing it in the next day or so.

**Comment by Traderain** [comment] 2016-12-19 12:11
When can this be expected to fixed?

**Comment by lolp1** [comment] 2016-12-23 19:48
@Traderain 

The bug is now fixed in the demo. Build the .sln and you should be set.

**Comment by Traderain** [comment] 2016-12-23 19:48
Thank you

**Comment by lolp1** [comment] 2016-12-23 19:50
@Traderain 
No problem. Please feel free to report any more bugs or if this bug is not fixed for you.

**Comment by Traderain** [comment] 2016-12-23 21:33
![image](https://i.gyazo.com/91ff74a634b8853ccc30ca19c54a5610.gif)

**Comment by lolp1** [comment] 2016-12-23 22:54
@Traderain 
Can you please try cleaning, then rebuilding the soultion, then placing ../debug contents from Overlay.NETs debug folder inside of the demos debug folder, then ensure one note pad is open only, and try again.

**Comment by Traderain** [comment] 2016-12-24 12:01
@lolp1 Did that still the same result

**Comment by lolp1** [comment] 2016-12-24 14:00
Seems to be working for me on the latest build.

https://www.youtube.com/watch?v=8Vv4s_ndV2Y&feature=youtu.be

**Comment by Traderain** [comment] 2016-12-24 16:05
Thats exactly what I did. I will try to troubleshoot it and report here if I can fix it so others know about it.

**Comment by lolp1** [comment] 2016-12-25 11:38
@Traderain  
Do you use x86 or x64 based pc?

**Comment by Traderain** [comment] 2016-12-25 20:55
x64

**Comment by lolp1** [comment] 2016-12-25 21:19
@Traderain 
Can you please try either 1. Compile with the option "prefer 32 bit" or 2. Try the overlay on a process you can ensure is a x64 process. I'd go with 1 and try it on notepad, as it is a x86 process despite the OS being x64 you use.

It is possible that is an issue with my Process.NET library not reading the window status correctly in a 32 bit process on a x64 OS if 32 bit is not preferred.

**Comment by Traderain** [comment] 2016-12-26 17:15
@lolp1 Tried it on my laptop which is Winows 10 and it works perfectly. Here is a snapshot of the details of my PC so you can troubleshoot the issue better.
![image](https://cloud.githubusercontent.com/assets/6411732/21484706/519c88a2-cb97-11e6-901d-0747edff9e4d.png)

**Comment by lolp1** [comment] 2016-12-26 19:08
Thanks for the report I'll look into it. The project was built with the latest libraries and .net frameworks in the latest visual studio, so it is possible there are some bugs in windows 7 I need to track down. I'll see what I can find.

**Comment by Traderain** [comment] 2017-01-04 21:04
Have you managed to come up with a fix? Sadly I can't switch my project's overlay library until this is fixed because I have many win7 users.

**Comment by toomtoomcheck** [comment] 2017-01-09 09:00
Hi,

Same issue here, If you reduce the windows it works perfectly, but if you switch windows without reducing it, it's still showing me overlay.

Regards

**Comment by lolp1** [comment] 2017-01-17 17:02
@Traderain @toomtoomcheck  Free time is on my side for a while (hopefully a long while!). I will be looking into the issue today and trying to fix. I will update my findings soon here.

**Comment by mattukdev** [comment] 2017-02-21 11:07
I also have this same issue on win 7 x64.

**Comment by MakariAeron** [comment] 2017-02-22 18:26
I've got the same problem too with Win7, Nvidia Quadro card here. I think it's something to do with how Win7 shows things. It's a shame because Win7 is still so widely used. I guess I'll stick with WPF for now.

**Comment by lolp1** [comment] 2017-03-17 08:15
As far as I can tell, this bug does not exist in windows 10 and the only windows 7 device I have access to can not reproduce it. I am going to close the issue for now (as I am going through and cleaning them up) as I only intend to support windows 10+ from this point on.

However, this does not mean I am not interested in fixing the bug. If it still exist on the latest version just committed, and you can provide more details, such as what happens while stepping through in debugger or any suspicious stacktraces, or any kind of fix, I will look into it/implement it/accept any pull request. Thanks

**Closed by lolp1** 2017-03-17 08:15 UTC
